### ISSUE TITLE
Ecowitt controller requires a restart when Home Assistant is restarted

### ISSUE THREAD

**Issue by chrisp250** [mplogas/ecowitt-controller#5]
I am running Ecowitt-controller on a separate server to Home Assistant. It runs on a docker compose stack alongside with mqtt.

After updating Home Assistant to the latest version, the weather station data was not coming through. After taking docker compose down and back up again, the data started to come through.

I also have a solar panel monitor over mqtt and this does not get affected when I restart Home Assistant.

Thank you

**Comment by mplogas** [comment]
Yeah, it's a limitation of my dotnet HA MQTT library. I observed that behavior as well. I already started working on it (subscribing to HomeAssistant topic and re-publishing once it goes offline) but then another (christmas related) project took my full attention 

 An easy fix would be just enabling retain, but this leads to possible side effects, e.g. the last sensor state will be stored on the broker- so an offline device would always show the last received value,
 Any thoughts?

**Comment by chrisp250** [comment]
I don't have a much experience with Home Assistant and MQTT. This is limited to an integration I wrote for my airconditioner that uses MQTT.

I don't use auto discovery. I configure the MQTT variables manually like so:

```
mqtt:
  - climate:
      name: Studio Climate
      unique_id: studio.ac
      modes:
        - "off"
        - "cool"
        - "dry"
        - "heat"
        - "fan_only"
        - "auto"
      fan_modes:
        - "auto"
        - "Quiet"
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"        
      temperature_command_topic: "climate/studio/temperaturecommand"
      current_humidity_topic: "climate/studio/humidity"
      current_temperature_topic: "climate/studio/temperature"
      temperature_state_topic: "climate/studio/temperaturesp"
      mode_state_topic: "climate/studio/mode"
      mode_command_topic: "climate/studio/modecommand"
      fan_mode_state_topic: "climate/studio/fanmode"      
      precision: 0.5
```

The behaviour I notice is different too. The integration doesn't care the state of Home Assistant. You can shut it down, restart it, etc. It will keep sending data to MQTT. Once Home Assistant comes back it will start listening for events on MQTT and will populate all the entities. So I'm not sure why this integration needs to be restarted if Home Assistant is restarted. I thought one would be independent from the other and the integration wouldn't care whether Home Assistant is there or not.
It's also worth noting my integration is written in Python.
Cheers
